name: ollyjrobinson
favicon: null
layout_spectrum: 0.21726665692403913
typography_spectrum: 0.27689870772883296
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.31411527725867927
  lightness: 0.3383610974997282
  saturation: 0.5078649513889104
  rhythmicContrast: 0.7778124241158366
purpose: []
